### ISSUE TITLE
ERROR: Error: image catshop/catshop:lastest not found

### ISSUE THREAD

**Issue by dovexiaoxin** [catworking/catshop#6]
[root@evod catshop-master]# docker-compose up -d --force-recreate --remove-orphans --build
Pulling drupal (registry.cn-hangzhou.aliyuncs.com/catshop/catshop:lastest)...
Trying to pull repository registry.cn-hangzhou.aliyuncs.com/catshop/catshop ... 
Pulling repository registry.cn-hangzhou.aliyuncs.com/catshop/catshop
ERROR: Error: image catshop/catshop:lastest not found

**Comment by solody** [comment]
I'm planing to fix this. refer to [https://github.com/catworking/catshop/issues/3](https://github.com/catworking/catshop/issues/3)
